name: Imprime data atual

on:
  push:

jobs:
  imprime_data_ubunto:
    name: Imprime data atual
    runs-on: ubuntu-latest
    
    steps: 
      - name: Imprime data atual - Ubuntu
      run: date
    
